stages:
  - build
  - test
  - review

build:
  stage: build
  script:
    - echo 'Building'

tests:
  stage: test
  script:
    - echo 'Testing 1'

linters:
  stage: test
  script:
    - echo 'Testing 2'

autodeploy dev:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com
